feat(cicd): fail pipeline if code check failed
Fail linter job if the code quaility score is lower than expected.

diff --git a/cicd/jobs/linter.gitlab-ci.yml b/cicd/jobs/linter.gitlab-ci.yml
--- a/cicd/jobs/linter.gitlab-ci.yml
+++ b/cicd/jobs/linter.gitlab-ci.yml
@@ -1,3 +1,8 @@
+variables:
+  MINIMUM_CODE_QUALITY_SCORE:
+    description: "Minimum pylint score to pass Code Quality Gate"
+    value: "9"
+
 .linter:
   cache:
     key: $CI_COMMIT_REF_SLUG
@@ -13,7 +18,17 @@
     - echo "Running pylint..."
     - pylint bookshop_app/
     - echo "Post-processing pylint artifacts..."
-    - echo "pylint-score $(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint_parseable_report.txt)" > ../pylint_metric.txt
+    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint_parseable_report.txt)
+    - echo "pylint-score $PYLINT_SCORE" > ../pylint_metric.txt
+    - >
+      if python -c "exit(0 if $PYLINT_SCORE > $MINIMUM_CODE_QUALITY_SCORE else 0)";
+      then 
+        echo "Code Quality Gate passed. Current: $PYLINT_SCORE. Expected: >$MINIMUM_CODE_QUALITY_SCORE"
+        exit 0
+      else
+        echo "Code Quality Gate failed. Current: $PYLINT_SCORE. Expected: >$MINIMUM_CODE_QUALITY_SCORE" 
+        exit 1
+      fi
   artifacts:
     paths:
       - pylint_metric.txt
